added ui change for possible payout
moonshotcollective/quadratic-diplomacy pull request #132
Opened 2022-02-03 13:40 UTC by tricelex

added ui change for possible payout #120

2022-02-07 18:37 UTC, xordist requested changes

2022-02-07 18:37 UTC, hansmrtn commented on packages/react-app/src/routes/party/components/ViewTable.jsx
> +                <Center>{!isNaN(dist[d]) ? (dist[d] * amountToDistribute).toFixed(2) : amountToDistribute}</Center>
I'd like to see this column hid if the amountToDistribute is nil. Always showing "possible payout" is misleading until an actual distribution is taking place.

2022-02-07 18:37 UTC, hansmrtn commented on packages/react-app/src/routes/party/components/ViewTable.jsx
> +              <Center>{"possible payout"}</Center>
Consider renaming to just "Payout" as the user should assume that what is being shown is accurate.

2022-02-08 06:14 UTC, tricelex commented on packages/react-app/src/routes/party/components/ViewTable.jsx
> +                <Center>{!isNaN(dist[d]) ? (dist[d] * amountToDistribute).toFixed(2) : amountToDistribute}</Center>
fixed in latest commit.

2022-02-08 06:15 UTC, tricelex commented on packages/react-app/src/routes/party/components/ViewTable.jsx
> +              <Center>{"possible payout"}</Center>
renamed in latest commit.

2022-02-08 22:44 UTC, hansmrtn approved these changes

2022-02-08 22:44 UTC, merged