Add tooltip
moonshotcollective/quadratic-diplomacy pull request #133
Opened 2022-02-03 18:04 UTC by Nazeeh21

Closes #63

This is a draft PR. Feel free to suggest changes and improvements

2022-02-07 05:54 UTC, Nazeeh21 commented
@xordist LMKYT on this

2022-02-07 18:38 UTC, xordist requested changes

2022-02-07 18:38 UTC, hansmrtn commented on packages/react-app/src/components/Header.jsx
> +          <Tooltip label="Tool to distribute compensation to team members based on democratic principles">
I do not think this is a necessary tooltip and should probably be removed before merging.

2022-02-07 18:38 UTC, hansmrtn commented on packages/react-app/src/routes/create/Create.jsx
> +          <Tooltip label="Voters are persons who vote for the candidates">Voters: </Tooltip>
It would be great to see this (and the other labels) have a small question mark button next to the text, that on hover shows helpful information e.g see icons: https://chakra-ui.com/docs/media-and-icons/icon

2022-02-08 13:05 UTC, naz3eh commented on packages/react-app/src/routes/create/Create.jsx
> +          <Tooltip label="Voters are persons who vote for the candidates">Voters: </Tooltip>
I've added a question mark icon that will show the tooltip on hover. LMK if more changes are required

2022-02-08 13:05 UTC, Nazeeh21 commented on packages/react-app/src/components/Header.jsx
> +          <Tooltip label="Tool to distribute compensation to team members based on democratic principles">
Removed

2022-02-08 20:00 UTC, hansmrtn submitted a review, later dismissed
Looks good.

2022-02-08 21:07 UTC, merged